/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ascem;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class AscemApp {
    public static void main(String[] args) {
        SpringApplication.run(AscemApp.class, args);
    }
}
